paths:
  imaging_raw: "data/raw/imaging"
  imaging_processed: "data/processed/imaging"
  genomics_raw: "data/raw/genomics.csv"
  genomics_processed: "data/processed/genomics.csv"

model:
  cnn_filters: [32, 64]
  dense_units: 128
  dropout: 0.3
  epochs: 25
  batch_size: 32
